# Generated by Django 2.1.3 on 2018-11-13 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(help_text='Category description')),
                ('is_featured', models.BooleanField(default=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='category')),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(help_text='Main category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='category_app.Category')),
            ],
        ),
    ]
