# Generated by Django 2.1.3 on 2018-11-13 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0002_auto_20181113_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Main category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='category_app.Category'),
        ),
    ]
