# Generated by Django 2.1.3 on 2018-11-13 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0003_auto_20181113_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg'])]),
        ),
    ]
