# Generated by Django 2.1.3 on 2018-11-13 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0005_auto_20181113_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category'),
        ),
    ]
