# Generated by Django 2.1.3 on 2018-11-13 14:16

import category_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category_app', '0006_auto_20181113_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category', validators=[category_app.models.validate_image]),
        ),
    ]
